// import "./globals.css";
// import "../../styles/layout";
// import "../../styles/layout.css"
import { Source_Sans_3, Source_Code_Pro } from "next/font/google";
//这里原本是next/font/google,但是编辑器会报错说找不到相关模块，改成@next后报错消失，但说不定会有另外bug
const sourceSans3 = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-sans",
});

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-code",
});

export const metadata = {
  title: "BlockAGI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${sourceCodePro.variable} ${sourceSans3.variable}`}>
        {children}
      </body>
    </html>
  );
}
